name: qiitaapp
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_html: ^2.2.1
  http: ^0.13.0
  intl: ^0.17.0
  package_info: ^2.0.0
  shared_preferences: ^2.0.4
  uni_links: ^0.5.1
  url_launcher: ^6.0.2
dependency_overrides:
  url_launcher_web: 2.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2

flutter:
  uses-material-design: true

flutter_icons:
  image_path: 'assets/icon.png'
  android: true
  ios: true
  adaptive_icon_background: '#ffffff'
  adaptive_icon_foreground: 'assets/icon.png'
